src/br/com/hjrnet/desafiointercase/mb/MalhaLogisticaBean.java
package br.com.hjrnet.desafiointercase.mb;

import java.io.Serializable;
import java.util.List;

import javax.annotation.ManagedBean;




//import org.primefaces.model.chart.PieChartModel;




import br.com.hjrnet.desafiointercase.dao.MalhaLogisticaDao;
import br.com.hjrnet.desafiointercase.modelo.MalhaLogistica;

/**
 * @author hjrnet
 * Controle de persistencia, CRUD.
 */
@ManagedBean
public class MalhaLogisticaBean implements Serializable {

	private static final long serialVersionUID = -1957176543273170800L;

	private List<MalhaLogistica> malhas;

	private MalhaLogistica malha = new MalhaLogistica();
	
	private Long malhaId;
	
	
	private MalhaLogisticaDao dao = new MalhaLogisticaDao();

	public String grava(){
		MalhaLogisticaDao dao = new MalhaLogisticaDao();
		if (malha.getId() == null){
			dao.adiciona(malha);
		} else {
			dao.atualiza(malha);
		}		
	
	     this.malhas = dao.listaTodos();

	     this.malha=new MalhaLogistica();
		
		return "index?faces-redirect=true";
	}
	
	public void carregaMalha(){
		if (malhaId != null && malhaId != 0){
			this.malha = dao.buscaPorId(this.malhaId);
		}
	}
	
	public List<MalhaLogistica> getMalhaLogisticas(){
		if (malhas==null){
			System.out.println("Carregando produtos...");
			malhas = new MalhaLogisticaDao().listaTodos();
		
		}
		return malhas;
	}
	
	public void remove(MalhaLogistica malha){
		MalhaLogisticaDao dao = new MalhaLogisticaDao();
		
		dao.remove(malha);
		this.malhas = dao.listaTodos();
		this.malha = new MalhaLogistica();
	}
	
	public void limpa(){
		MalhaLogisticaDao dao = new MalhaLogisticaDao();
		
		this.malhas = dao.listaTodos();
		this.malha = new MalhaLogistica();
	}

	
	public String cancela(){
		System.out.println("Cancela edição");
		this.malha = new MalhaLogistica();
		return "malha";
	}


	public List<MalhaLogistica> getMalhas() {
		return malhas;
	}


	public MalhaLogistica getMalha() {
		return malha;
	}


	public void setMalha(MalhaLogistica malha) {
		this.malha = malha;
	}


	public Long getMalhaId() {
		return malhaId;
	}


	public void setMalhaId(Long malhaId) {
		this.malhaId = malhaId;
	}


	public MalhaLogisticaDao getDao() {
		return dao;
	}


	public void setDao(MalhaLogisticaDao dao) {
		this.dao = dao;
	}


	public void setMalhas(List<MalhaLogistica> malhas) {
		this.malhas = malhas;
	}


}

WebContent/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:body>
		<f:metadata>
			<f:viewParam name="malha.id" value="#{malhaLogisticaBean.malhaId}"/>
			<f:viewAction action="#{malhaLogisticaBean.carregaMalha}"/>
		</f:metadata>
		
	 <h:form id="formMalha">
			
				<h:messages autoUpdate="true" />
				<h:inputHidden value="#{malhaLogisticaBean.malha.id}"/>
				<h2>
					<h:outputText value="Novo Malha" rendered="#{empty alhaLogisticaBean.malha.id}"/>
					<h:outputText value="Editar Malha" rendered="#{not empty alhaLogisticaBean.malha.id}"/>
				</h2>
				<fieldset>
				<legend>Dados da Malha</legend>
					
					<h:outputLabel value="Nome" for="nome"></h:outputLabel>
					<h:inputTextarea id="nome" value="#{malhaLogisticaBean.malha.nome}"/>
		
					<h:outputLabel value="Origem" for="origem"></h:outputLabel>
					<h:inputTextarea id="origem" value="#{malhaLogisticaBean.malha.origem}"/>
		
					<h:outputLabel value="Destino" for="destino"></h:outputLabel>
					<h:inputTextarea id="destino" value="#{malhaLogisticaBean.malha.destino}"/>
		
					<h:outputLabel value="Distancia" for="distancia"></h:outputLabel>
					<h:inputTextarea id="distancia" value="#{malhaLogisticaBean.malha.distancia}"/>
		
					<h:inputHidden>
					</h:inputHidden>
		
					<h:commandButton value="Gravar" action="#{malhaLogisticaBean.grava}"/>
					<h:commandButton value="Limpar" action="#{malhaLogisticaBean.limpa}"/>
					<h:commandButton value="Cancelar edição" action="#{malhaLogisticaBean.cancela}"/>
				</fieldset>
				
				
			</h:form>
			
			<h:form id="formTabela">
				<h2>Listagem de Malha</h2>
			 	<h:dataTable value="#{malhaLogisticaBean.malhaLogisticas}" var="malha"  >
				  
				    <h:column>
						<f:facet name="header">Nome</f:facet>
						#{malha.nome}
					</h:column> 
					
					<h:column>
						<f:facet name="header">Origem</f:facet>
						#{malha.origem}
					</h:column>
					
					<h:column>
						<f:facet name="header">Destino</f:facet>
						#{malha.destino}
					</h:column>
					
					<h:column>
						<f:facet name="header">Distancia</f:facet>
						#{malha.distancia} 
					</h:column>
					
					<h:column>
						<f:facet name="header">Ações</f:facet>
						<h:commandLink value="Alterar">
							<f:setPropertyActionListener value="#{malha}" target="#{malhaLogisticaBean.malha}"/>
						</h:commandLink>
						&nbsp;
						<h:commandLink action="#{malhaLogisticaBean.remove(malha)}" value="Remover">
							<f:ajax render=":formMalha :formTabela"/>
						</h:commandLink>
						&nbsp;
						<h:outputLink value="index.xhtml">
							<h:outputText value="Editar Produto via GET"/>
							<f:param name="malha.id" value="#{malha.id}"/>
						</h:outputLink>
					</h:column>
						</h:dataTable> 
			
			 	</h:form>
</h:body>
</html>

WebContent/resources/caelum/campoTexto.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:cc="http://java.sun.com/jsf/composite">

	<cc:interface>
		<cc:attribute name="id" required="true"/>
		<cc:attribute name="label" required="true"/>
		<cc:attribute name="value"/>
	</cc:interface>
	
	<cc:implementation>
		<h:message for="#{cc.attrs.id}"/>
		<h:outputLabel value="#{cc.attrs.label}" for="#{cc.attrs.id}"/>
		<h:inputText id="#{cc.attrs.id}" value="#{cc.attrs.value}"/>
	</cc:implementation>
</html>